apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra1
  source:
    repoURL: https://wiktorvip.github.io/k8s-lab-bootstrap
    chart: metallb-config
    targetRevision: '0.2.0'    # helm search repo XXX --versions
    helm:
      releaseName: metallb-config
      values: |
        metallbConfig:
          name: metallb-default
          ipAddresses: 10.0.0.240-10.0.0.250
  destination:
    namespace: metallb-system
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true