apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 1
  labels:
    app: custom-alert-rules
  name: custom-alert-rules
  namespace: monitoring-system
spec:
  endpoints:
  - port: http
  namespaceSelector:
    matchNames:
    - monitoring-system
  selector:
    matchLabels:
      role: custom-alert-rules
