apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2024-10-14T10:20:42Z"
  generation: 1
  labels:
    app: custom-alert-rules
  name: custom-alert-rules
  namespace: monitoring-system
spec:
  endpoints:
  - enableHttp2: true
    path: /metrics
    port: http-web
  - path: /metrics
    port: reloader-web
  namespaceSelector:
    matchNames:
    - monitoring-system
  selector:
    matchLabels:
      role: custom-alert-rules
