apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.6.10
    helm:
      releaseName: argo-cd
      values: |
        crds:
          install: true
        redis-ha:
          enabled: false
        dex:
          enabled: false
        server:
          replicas: 1
          service:
            type: NodePort
            nodePortHttp: 30888
            nodePortHttps: 30889
  destination:
    name: in-cluster
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true