apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 65.1.1
    helm:
      releaseName: kube-prometheus-stack
      values: |
         alertmanager:
           enabled: true
           service:
             type: NodePort
             nodePort: 30903
         defaultRules:
           create: true
           rules:
             etcd: false
         grafana:
           enabled: true
           service:
             type: NodePort
             nodePort: 30998
           adminUser: admin
           adminPassword: admin123
           additionalDataSources:
           - access: proxy
             isDefault: false
             name: loki
             orgId: 1
             type: loki
             url: http://loki-stack.loki-system:3100
             version: 1
         kubeEtcd:
           enabled: false
         kubeScheduler:
           enabled: false
         prometheus:
           enabled: true
           service:
             type: NodePort
             nodePort: 30090
           prometheusSpec:
             storageSpec:
               volumeClaimTemplate:
                 spec:
                   accessModes:
                     - ReadWriteOnce
                   resources:
                     requests:
                       storage: 5Gi
                   storageClassName: nfs-storage
         prometheusOperator:
           enabled: true
  destination:
    name: in-cluster
    namespace: monitoring-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true