apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 7.2.1
    helm:
      releaseName: velero
      values: |
        configuration:
          backupStorageLocation:
          - bucket: minio
            name: minio
            provider: aws
            default: true
            config:
              region: minio
              s3ForcePathStyle: true
              s3Url: http://172.16.200.30:9000
          volumeSnapshotLocation:
          - config:
              region: minio
              s3ForcePathStyle: true
              s3Url: http://172.16.200.30:9000
            provider: aws
        initContainers:
        - name: velero-plugin-for-aws
          image: velero/velero-plugin-for-aws:v1.10.1
          volumeMounts:
          - mountPath: /target
            name: plugins
        credentials:
          name: minio-credentials
          useSecret: true
          secretContents:
            cloud: |
              [default]
              aws_access_key_id=velero
              aws_secret_access_key=velero1234
  destination:
    name: in-cluster
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true