apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: infra2
  source:
    chart: consul
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 1.6.1
    helm:
      releaseName: consul
      values: |
        global:
          enabled: true
          name: consul 
  destination:
    name: in-cluster
    namespace: consul
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true