---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-default
  namespace: metallb-system
spec:
  addresses:
  - 172.16.200.240-172.16.200.250
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-default
  namespace: metallb-system
spec:
  ipAddressPools:
  - metallb-default