apiVersion: v2
name: metallb-umbrella
description: A Helm chart for Kubernetes

type: application

version: 0.2.0

appVersion: "0.2.0"

dependencies:
- name: metallb
  version: 0.14.8
  repository: https://metallb.github.io/metallb

# https://github.com/metallb/metallb/releases
